name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [1.2]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Cypress Test Suite
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true
          env: grepTags=@smoke
        env:
          CYPRESS_RECORD_KEY: '28ea28a6-7188-4a74-b4d7-d11b834e08b7'
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
